apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: bedrock-chat-v2
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup
            image: mysql:8.0
            command:
            - /bin/bash
            - -c
            - |
              DATE=$(date +%Y%m%d_%H%M%S)
              mysqldump -h mysql -uroot -proot_password bedrock_chat > /backup/backup_${DATE}.sql
              echo "Backup completed: backup_${DATE}.sql"
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
            env:
            - name: MYSQL_PWD
              value: "root_password"
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
          restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: bedrock-chat-v2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
