apiVersion: v1
kind: ResourceQuota
metadata:
  name: bedrock-chat-quota
  namespace: bedrock-chat-v2
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "10"
    limits.memory: 16Gi
    persistentvolumeclaims: "5"
    pods: "20"
    services: "10"
