apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bedrock-chat-metrics
  namespace: bedrock-chat
  labels:
    app: bedrock-chat
spec:
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
