# Network Policies for Bedrock Chat Application
# Provides secure network segmentation between services

---
# Allow all traffic within bedrock-chat namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-namespace-traffic
  namespace: bedrock-chat-v2
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: bedrock-chat
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: bedrock-chat

---
# Allow external access to frontend via ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-ingress
  namespace: bedrock-chat-v2
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  - from: []  # Allow external traffic
    ports:
    - protocol: TCP
      port: 3000

---
# Allow API Gateway to communicate with backend services
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-gateway-backend
  namespace: bedrock-chat-v2
spec:
  podSelector:
    matchLabels:
      app: api-gateway
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: bedrock-service
    ports:
    - protocol: TCP
      port: 9000
  - to:
    - podSelector:
        matchLabels:
          app: file-service
    ports:
    - protocol: TCP
      port: 7000
  - to:
    - podSelector:
        matchLabels:
          app: mysql
    ports:
    - protocol: TCP
      port: 3306

---
# Allow bedrock-service to access external AWS services
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-bedrock-aws-access
  namespace: bedrock-chat-v2
spec:
  podSelector:
    matchLabels:
      app: bedrock-service
  policyTypes:
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api-gateway
    ports:
    - protocol: TCP
      port: 9000
  egress:
  - to: []  # Allow all external traffic for AWS API calls
    ports:
    - protocol: TCP
      port: 443  # HTTPS for AWS APIs
    - protocol: TCP
      port: 80   # HTTP if needed

---
# Allow file-service database access
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-file-service-db
  namespace: bedrock-chat-v2
spec:
  podSelector:
    matchLabels:
      app: file-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api-gateway
    ports:
    - protocol: TCP
      port: 7000
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: mysql
    ports:
    - protocol: TCP
      port: 3306

---
# Allow MySQL to accept connections from backend services
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mysql-access
  namespace: bedrock-chat-v2
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api-gateway
  - from:
    - podSelector:
        matchLabels:
          app: file-service
    ports:
    - protocol: TCP
      port: 3306

---
# Allow DNS resolution for all pods
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: bedrock-chat-v2
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
