apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-uploads-pv
  namespace: bedrock-chat-v2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /var/lib/bedrock-files
    type: DirectoryOrCreate
