apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: bedrock-chat
  labels:
    app: file-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      serviceAccountName: bedrock-chat-sa
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ['sh', '-c', 'mkdir -p /app/uploads && chown -R 999:999 /app/uploads && chmod -R 755 /app/uploads']
        volumeMounts:
        - name: file-uploads
          mountPath: /app/uploads
      containers:
      - name: file-service
        image: samitsinghhh/langchain-4:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_URL
        - name: UPLOAD_DIR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: UPLOAD_DIR
        - name: QA_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: QA_SERVICE_URL
        volumeMounts:
        - name: file-uploads
          mountPath: /app/uploads
        livenessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: file-uploads
        hostPath:
          path: /var/lib/bedrock-files
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: file-service
  namespace: bedrock-chat
spec:
  selector:
    app: file-service
  ports:
  - port: 7000
    targetPort: 7000
    name: http
  type: ClusterIP
