apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: bedrock-chat
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: bedrock-chat-sa
      containers:
      - name: api-gateway
        image: samitsinghhh/langchain-2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_URL
        - name: BEDROCK_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BEDROCK_SERVICE_URL
        - name: FILE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FILE_SERVICE_URL
        - name: QA_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: QA_SERVICE_URL
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            memory: "96Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: bedrock-chat
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
