apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
  namespace: bedrock-chat-v2
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJzYW1pdHNpbmdoaGgiLCJwYXNzd29yZCI6ImRja3JfcGF0XzZld2NCRVNOVlIxVUpwa1ZoQWtOcThBS0ZMdyJ9fX0=

