apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: langchain-app
  labels:
    app: file-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      imagePullSecrets:
        - name: docker-hub-secret
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ['sh', '-c', 'mkdir -p /app/uploads && chown -R 999:999 /app/uploads && chmod -R 755 /app/uploads']
        volumeMounts:
        - name: file-uploads
          mountPath: /app/uploads
      containers:
        - name: file-service
          image: samitsinghhh/langchain-4:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_URL
            - name: UPLOAD_DIR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: UPLOAD_DIR
            - name: QA_SERVICE_URL
              value: "http://intelligent-qa-service:6000"
          volumeMounts:
            - name: file-uploads
              mountPath: /app/uploads
          startupProbe:
            httpGet:
              path: /health
              port: 7000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 7000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 7000
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: file-uploads
          hostPath:
            path: /tmp/file-uploads
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: file-service
  namespace: langchain-app
  labels:
    app: file-service
spec:
  ports:
  - port: 7000
    targetPort: 7000
    name: http
  selector:
    app: file-service
  type: ClusterIP
