apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligent-qa-service
  namespace: langchain-app
  labels:
    app: intelligent-qa-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intelligent-qa-service
  template:
    metadata:
      labels:
        app: intelligent-qa-service
    spec:
      imagePullSecrets:
        - name: docker-hub-secret
      containers:
        - name: intelligent-qa-service
          image: samitsinghhh/langchain-5:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_URL
            - name: BEDROCK_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BEDROCK_SERVICE_URL
            - name: FILE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FILE_SERVICE_URL
          startupProbe:
            httpGet:
              path: /health
              port: 6000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 6000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 6000
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: intelligent-qa-service
  namespace: langchain-app
spec:
  selector:
    app: intelligent-qa-service
  ports:
    - port: 6000
      targetPort: 6000
  type: ClusterIP
