# Bedrock Service Horizontal Pod Autoscaler
# Scales Bedrock service pods based on CPU utilization
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bedrock-service-hpa
  namespace: bedrock-chat-v2
  labels:
    app: bedrock-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bedrock-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # Longer stabilization for AI workloads
      policies:
      - type: Percent
        value: 25  # Conservative scale down
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
