apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bedrock-service-hpa
  namespace: bedrock-chat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bedrock-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 120
