apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bedrock-chat-v2
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: docker-hub-secret
      containers:
        - name: frontend
          image: samitsinghhh/frontend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REACT_APP_API_URL
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: "48Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "100m"

