apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bedrock-chat
  labels:
    app: frontend
spec:
  replicas: 1  # Reduced from 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: samitsinghhh/frontend:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REACT_APP_API_URL
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 8
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"     # Reduced from 128Mi
            cpu: "50m"         # Reduced from 100m
          limits:
            memory: "256Mi"    # Reduced from 512Mi
            cpu: "200m"        # Reduced from 500m
