apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: bedrock-chat-v2
  labels:
    app: api-gateway
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app: api-gateway
  type: ClusterIP
