apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: bedrock-chat
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    app: mysql
  type: ClusterIP
