apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-uploads-pvc
  namespace: bedrock-chat-v2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  volumeMode: Filesystem
