# Quick fix MySQL StatefulSet using hostPath instead of PVC
# This is for development/testing - not recommended for production
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: bedrock-chat-v2
  labels:
    app: mysql
spec:
  serviceName: mysql-headless
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root_password"
        - name: MYSQL_DATABASE
          value: "bedrock_chat"
        - name: MYSQL_USER
          value: "bedrock_user"
        - name: MYSQL_PASSWORD
          value: "bedrock_password"
        args:
        - --default-authentication-plugin=mysql_native_password
        - --innodb-buffer-pool-size=128M
        - --max-connections=100
        - --innodb-buffer-pool-instances=1
        - --innodb-log-file-size=32M
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - 'mysqladmin ping -h localhost -u root -proot_password'
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 20
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - 'mysqladmin ping -h localhost -u root -proot_password'
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - 'mysql -h localhost -u root -proot_password -e "SELECT 1"'
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: mysql-data
        hostPath:
          path: /tmp/mysql-data
          type: DirectoryOrCreate
      - name: init-script
        configMap:
          name: mysql-init-script
