# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Apply K8s files
      run: |
        kubectl apply -f k8s/01-namespace.yaml
        
        # Create secrets
        kubectl create secret generic aws-secrets \
          --from-literal=AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
          --from-literal=AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -n bedrock-chat --dry-run=client -o yaml | kubectl apply -f -
        
        kubectl create secret generic mysql-secrets \
          --from-literal=MYSQL_ROOT_PASSWORD="root_password" \
          --from-literal=MYSQL_DATABASE="bedrock_chat" \
          --from-literal=MYSQL_USER="bedrock_user" \
          --from-literal=MYSQL_PASSWORD="bedrock_password" \
          -n bedrock-chat --dry-run=client -o yaml | kubectl apply -f -
        
        kubectl apply -f k8s/03-configmap.yaml
        kubectl apply -f k8s/04-rbac.yaml
        
        # Deploy MySQL first and wait
        kubectl apply -f k8s/05-mysql-fixed.yaml
        kubectl wait --for=condition=ready pod -l app=mysql -n bedrock-chat --timeout=300s
        
        # Deploy other services
        kubectl apply -f k8s/06-bedrock-service.yaml
        kubectl apply -f k8s/07-file-service-hostpath.yaml
        kubectl apply -f k8s/08-qa-service-fixed.yaml
        
        # Wait for dependencies before API Gateway
        kubectl wait --for=condition=ready pod -l app=bedrock-service -n bedrock-chat --timeout=180s
        kubectl wait --for=condition=ready pod -l app=file-service -n bedrock-chat --timeout=180s
        kubectl wait --for=condition=ready pod -l app=intelligent-qa-service -n bedrock-chat --timeout=180s
        
        # Deploy API Gateway last
        kubectl apply -f k8s/09-api-gateway-updated.yaml
        kubectl apply -f k8s/10-frontend-simple-proxy.yaml
        
        # Show final status
        kubectl get pods -n bedrock-chat
